name: 'customers_transactions'
version: '1.0.0'

profile: 'main_db'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  customers_transactions:
    dim_customer_acquisition:
      +pre-hook: "TRUNCATE TABLE dim_customer_acquisition"
      +materialized: table
    cube_customer_transaction_behavior:
      +pre-hook: "TRUNCATE TABLE cube_customer_transaction_behavior"
      +materialized: table
